version: "3.9"  # optional since v1.27.0
services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    image: webapp:8.0
    ports:
      - "5000:5000"
    restart: always
    networks: 
     - webnet
    volumes:
      - .:/web
    links:
      - db

  db:
    image: mongo:latest
    hostname: test_mongodb
    environment:
      - MONGO_INITDB_DATABASE=developer_db
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=pass
    volumes:
      - ./init-db.js:/docker-entrypoint-initdb.d/init-db.js:ro
    ports:
      - 27017:27017
     
networks:
  webnet: